# coding: utf-8

"""
    Words

    Words API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sgrade@users.noreply.github.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.word_api import WordApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWordApi(unittest.TestCase):
    """WordApi unit test stubs"""

    def setUp(self):
        self.api = api.word_api.WordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_word(self):
        """Test case for add_word

        Add a new word to the store  # noqa: E501
        """
        pass

    def test_delete_word(self):
        """Test case for delete_word

        Deletes a word  # noqa: E501
        """
        pass

    def test_get_word_by_id(self):
        """Test case for get_word_by_id

        Find word by ID  # noqa: E501
        """
        pass

    def test_update_word(self):
        """Test case for update_word

        Update an existing word  # noqa: E501
        """
        pass

    def test_update_word_with_form(self):
        """Test case for update_word_with_form

        Updates a word in the store with form data  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        uploads an image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
