# coding: utf-8

"""
    Words

    Words API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sgrade@users.noreply.github.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.store_api import StoreApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStoreApi(unittest.TestCase):
    """StoreApi unit test stubs"""

    def setUp(self):
        self.api = api.store_api.StoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_order(self):
        """Test case for delete_order

        Delete purchase order by ID  # noqa: E501
        """
        pass

    def test_get_inventory(self):
        """Test case for get_inventory

        Returns word inventories by status  # noqa: E501
        """
        pass

    def test_get_order_by_id(self):
        """Test case for get_order_by_id

        Find purchase order by ID  # noqa: E501
        """
        pass

    def test_place_order(self):
        """Test case for place_order

        Place an order for a word  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
