# coding: utf-8

"""
    Words

    Words API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sgrade@users.noreply.github.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.word import Word  # noqa: E501
from swagger_client.rest import ApiException


class TestWord(unittest.TestCase):
    """Word unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWord(self):
        """Test Word"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.word.Word()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
