# coding: utf-8

"""
    Words

    Words API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sgrade@users.noreply.github.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.words_api import WordsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWordsApi(unittest.TestCase):
    """WordsApi unit test stubs"""

    def setUp(self):
        self.api = api.words_api.WordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_words_by_name(self):
        """Test case for find_words_by_name

        Find Words by name  # noqa: E501
        """
        pass

    def test_find_words_by_status(self):
        """Test case for find_words_by_status

        Finds Words by status  # noqa: E501
        """
        pass

    def test_get_words_to_learn(self):
        """Test case for get_words_to_learn

        Get words to learn  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
